### ISSUE TITLE
Images published are upside down

### ISSUE THREAD

**Issue by Kam0ss** [sonia-auv/sonia-simulation#8]

**Comment by Kam0ss** [comment]
A quick fix would be to rotate 180 the Renderer of each camera.

**Comment by Kam0ss** [comment]
Now they are published in mirror.

**Comment by Kam0ss** [comment]
https://forum.unity.com/threads/getrawtexturedata-method-resulting-in-flipped-image-in-rviz.1148723/

https://forum.unity.com/threads/camera-intrinsic-matrix.1143137/

https://forum.unity.com/threads/publish-game-camera-stream-via-ros.1124503/

**Comment by kaowilly** [comment]
Problem seems to be fixed as of now.
https://stackoverflow.com/questions/35950660/unity-180-rotation-for-a-texture2d-or-maybe-flip-both
